services:
  # Uncomment this section and comment out the mysql section to use postgres instead of mysql
  #postgres:
    #restart: unless-stopped
    #image: postgres:14
    #hostname: postgres
    #volumes: 
    #  - semaphore-postgres:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_USER: semaphore
    #  POSTGRES_PASSWORD: semaphore
    #  POSTGRES_DB: semaphore
  # If you wish to use postgres, comment the mysql service section below 
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    env_file:
      - .env
    hostname: mysql
    network_mode: "host"  # Use host networking
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  semaphore:
    restart: unless-stopped
    network_mode: "host"  # Use host networking
    image: semaphoreui/semaphore:latest
    env_file:
      - .env
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_DB_HOST: ${SEMAPHORE_DB_HOST}
      SEMAPHORE_DB_PORT: 3306 # MySQL port
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${SEMAPHORE_DB}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      # SEMAPHORE_LDAP_ACTIVATED: 'no' # If you wish to use LDAP, set to: 'yes'
      # SEMAPHORE_LDAP_HOST: dc01.local.example.com
      # SEMAPHORE_LDAP_PORT: '636'
      # SEMAPHORE_LDAP_NEEDTLS: 'yes'
      # SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      # SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      # SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      # SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      ANSIBLE_HOST_KEY_CHECKING: "False"
      SEMAPHORE_TELEGRAM_ALERT: "true"  # Enable Telegram alerts
      SEMAPHORE_TELEGRAM_CHAT_ID: ${SEMAPHORE_TELEGRAM_CHAT_ID}
      SEMAPHORE_TELEGRAM_TOKEN: ${SEMAPHORE_TELEGRAM_TOKEN}
      TZ: America/New_York
    depends_on:
      - mysql # Keep MySQL dependency as is

volumes:
  semaphore-mysql: # to use postgres, switch to: semaphore-postgres
