---
- name: Run PBS backup Script
  hosts: servers
  become: yes  # Elevate privileges if needed
  tasks:
    - name: Run PBS backup script
      shell: /mnt/Apex/Scripts/pbs_backup/pbs_backup.sh
      args:
        chdir: /mnt/Apex/Scripts/pbs_backup  # Change directory before running the script
