---
- name: Force recreate in a specific directory using docker-compose
  hosts: servers
  become: yes
  tasks:
    - name: Force recreate and start containers in the specified location
      shell: "{{ docker_command }}-compose up -d --force-recreate"
      args:
        chdir: "{{ compose_dir }}"  # Directory specified in the inventory for docker-compose.yml


