---
- name: Restart Docker on Synology NAS
  hosts: servers  # Define your host or group in the inventory file
  become: true             # Run commands with sudo
  tasks:
    - name: Restart Docker service
      ansible.builtin.command:
        cmd: "systemctl restart pkg-ContainerManager-dockerd"
      become: true
      become_user: root
