# This playbook pulls the latest Docker images and restarts containers on multiple servers.
# Each server uses a unique Docker Compose directory specified in the inventory (see below).
# The universal .env file in the compose files provides the container tag and other variables.
---
- name: Update containers on all servers
  become: yes
  hosts: servers
  tasks:
    - name: Copy the universal .env file to the Docker Compose directory
      copy:
        src: "{{ env_file_path }}"
        dest: "{{ compose_dir }}/.env"
        remote_src: yes
        mode: '0644'

    - name: Pull new Docker images using docker-compose
      shell: "{{ docker_command }}-compose pull"
      args:
        chdir: "{{ compose_dir }}"

    - name: Stop and remove existing containers
      shell: "{{ docker_command }}-compose down --remove-orphans --volumes"
      args:
        chdir: "{{ compose_dir }}"

    - name: Recreate and start containers using docker-compose
      shell: "{{ docker_command }}-compose up -d"
      args:
        chdir: "{{ compose_dir }}"


# Ex inventory file
# [servers]
# 192.168.1.7 ansible_user=mac compose_dir=/home/mac/docker_volumes/beszel env_file_path=/mnt/Apex/env_files/beszel/.env docker_command="/bin/docker"
# 192.168.1.10 ansible_user=mac compose_dir=/volume1/Apex/docker_volumes/beszel env_file_path=/volume1/Apex/env_files/beszel/.env docker_command="/usr/local/bin/docker"
