# This playbook pulls the latest Docker images and restarts containers on multiple servers.
# Each server uses a unique Docker Compose directory specified in the inventory (see below).
# The universal .env file in the compose files provides the container tag and other variables.
---
- name: Update containers on all servers
  become: yes
  hosts: servers
  tasks:
    - name: Copy the universal .env file to the Docker Compose directory
      copy:
        src: "{{ env_file_path }}"  # Path to the .env file from the inventory (on remote server)
        dest: "{{ compose_dir }}/.env"
        remote_src: yes  # This tells Ansible the source file is on the remote server
        mode: '0644'

    - name: Pull new Docker images using the .env file
      shell: docker-compose pull
      args:
        chdir: "{{ compose_dir }}"

    - name: Recreate and start containers with the updated image tag
      shell: docker-compose up -d
      args:
        chdir: "{{ compose_dir }}"




# Ex inventory file
# [servers]
# 192.168.23.7 ansible_user=mac compose_dir=/home/mac/docker_volumes/dozzle
# 192.168.23.8 ansible_user=mac compose_dir=/home/mac/docker_volumes/dozzle

