# This playbook pulls the latest Docker images and restarts containers on multiple servers.
# Each server uses a unique Docker Compose directory specified in the inventory (see below).
# The universal .env file in the compose files provides the container tag and other variables.
---
- name: Update containers on all servers
  become: yes
  hosts: servers
  tasks:
    - name: Copy the universal .env file to the Docker Compose directory
      copy:
        src: "{{ env_file_path }}"
        dest: "{{ compose_dir }}/.env"
        remote_src: yes
        mode: '0644'

    - name: Check if 'docker-compose' or 'docker compose' should be used
      shell: "{{ docker_command | default('docker-compose') }} version"
      ignore_errors: yes
      register: docker_compose_check

    - name: Pull new Docker images using docker-compose or docker compose
      shell: |
        {% if docker_compose_check.rc == 0 %}
        {{ docker_command | default('docker-compose') }} pull
        {% else %}
        docker compose pull
        {% endif %}
      args:
        chdir: "{{ compose_dir }}"

    - name: Recreate and start containers with docker-compose or docker compose
      shell: |
        {% if docker_compose_check.rc == 0 %}
        {{ docker_command | default('docker-compose') }} up -d
        {% else %}
        docker compose up -d
        {% endif %}
      args:
        chdir: "{{ compose_dir }}"






# Ex inventory file
# [servers]
# 192.168.23.7 ansible_user=mac compose_dir=/home/mac/docker_volumes/dozzle
# 192.168.23.8 ansible_user=mac compose_dir=/home/mac/docker_volumes/dozzle

